### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by DipanshKhandelwal** [DipanshKhandelwal/my-zodiac-sign#2]

**Comment by esslamben** [comment]
I can add this 👍 any license in particular or just standard?

**Comment by DipanshKhandelwal** [comment]
@Esslamb Thanks. Go ahead with MIT LICENSE

**Comment by esslamben** [comment]
This has been done on https://github.com/DipanshKhandelwal/my-zodiac-sign/pull/7

**Comment by DipanshKhandelwal** [comment]
Completed by #12
